run-name: Test CyberArk Integration
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch test
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

 
jobs:
  cyberark-integration:
    permissions:
      id-token: 'write'
      contents: 'read'
    runs-on: ubuntu-latest
 
    steps:


      - name: Import Secrets using CyberArk Conjur Secret Fetcher
        uses: cyberark/conjur-action@v2.0.6
        with:
          url: https://devops-service.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: public-github-app-property-on
          secrets: data/vault/RobinB-SafeSecretHub/TestOutOfSync/password|password2
      
      - name: echo secrets
        run: |
          # echo ${password2} | sed 's/./& /g'
          env | sed 's/./& /g'
          # | sets the result into an env variable
